export interface Product {
  id: number;
  name: string;
  price: number;
  originalPrice?: number;
  category: 'bracelets' | 'necklaces' | 'earrings' | 'custom';
  images: string[];
  description: string;
  shortDescription: string;
  rating: number;
  reviewCount: number;
  inStock: boolean;
  featured?: boolean;
  bestSeller?: boolean;
  tags: string[];
  materials: string[];
}

export const products: Product[] = [
  {
    id: 1,
    name: "Rose Quartz Love Bracelet",
    price: 45.00,
    originalPrice: 60.00,
    category: "bracelets",
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80",
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80",
      "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800&q=80",
    ],
    description: "Handcrafted with genuine rose quartz beads and delicate gold accents, this bracelet embodies love, compassion, and feminine energy. Each bead is carefully selected and strung on durable elastic for comfortable everyday wear.",
    shortDescription: "Genuine rose quartz beads with gold accents",
    rating: 4.9,
    reviewCount: 127,
    inStock: true,
    featured: true,
    bestSeller: true,
    tags: ["rose quartz", "love", "crystal", "handmade"],
    materials: ["Rose Quartz", "14k Gold Fill", "Elastic"],
  },
  {
    id: 2,
    name: "Pearl Elegance Necklace",
    price: 78.00,
    category: "necklaces",
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80",
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=800&q=80",
    ],
    description: "A timeless piece featuring lustrous freshwater pearls arranged in a delicate cascade design. Perfect for both everyday elegance and special occasions.",
    shortDescription: "Freshwater pearls in cascade design",
    rating: 4.8,
    reviewCount: 89,
    inStock: true,
    featured: true,
    bestSeller: true,
    tags: ["pearl", "elegant", "classic"],
    materials: ["Freshwater Pearls", "Sterling Silver"],
  },
  {
    id: 3,
    name: "Boho Dream Earrings",
    price: 32.00,
    category: "earrings",
    images: [
      "https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=800&q=80",
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&q=80",
    ],
    description: "Colorful bohemian-inspired earrings featuring hand-dyed wooden beads and turquoise accents. Lightweight and perfect for adding a pop of color to any outfit.",
    shortDescription: "Colorful boho wooden beads",
    rating: 4.7,
    reviewCount: 64,
    inStock: true,
    featured: true,
    bestSeller: true,
    tags: ["boho", "colorful", "wooden"],
    materials: ["Wooden Beads", "Turquoise", "Hypoallergenic Hooks"],
  },
  {
    id: 4,
    name: "Moonstone Magic Bracelet",
    price: 52.00,
    category: "bracelets",
    images: [
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=80",
      "https://images.unsplash.com/photo-1622398925373-3f91b1e275f5?w=800&q=80",
    ],
    description: "Enchanting moonstone beads that shimmer with every movement, accented with tiny gold-filled rondelles. Said to bring intuition and emotional balance.",
    shortDescription: "Shimmering moonstone with gold accents",
    rating: 4.9,
    reviewCount: 156,
    inStock: true,
    featured: true,
    bestSeller: true,
    tags: ["moonstone", "crystal", "spiritual"],
    materials: ["Moonstone", "14k Gold Fill"],
  },
  {
    id: 5,
    name: "Golden Hour Layered Necklace",
    price: 65.00,
    originalPrice: 85.00,
    category: "necklaces",
    images: [
      "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=800&q=80",
      "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=800&q=80",
    ],
    description: "Three delicate chains layered to perfection, featuring tiny gold beads and a central pendant. The perfect statement piece for any outfit.",
    shortDescription: "Three-layer gold bead necklace",
    rating: 4.8,
    reviewCount: 92,
    inStock: true,
    featured: true,
    bestSeller: true,
    tags: ["layered", "gold", "statement"],
    materials: ["14k Gold Fill", "Brass"],
  },
  {
    id: 6,
    name: "Amethyst Serenity Earrings",
    price: 38.00,
    category: "earrings",
    images: [
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&q=80",
      "https://images.unsplash.com/photo-1588444837495-c6cfeb53f32d?w=800&q=80",
    ],
    description: "Deep purple amethyst beads dangle elegantly from sterling silver hooks. Known for their calming properties and stunning natural color variations.",
    shortDescription: "Purple amethyst with sterling silver",
    rating: 4.9,
    reviewCount: 78,
    inStock: true,
    featured: true,
    tags: ["amethyst", "purple", "calming"],
    materials: ["Amethyst", "Sterling Silver"],
  },
  {
    id: 7,
    name: "Custom Friendship Bracelet Set",
    price: 55.00,
    category: "custom",
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80",
      "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=800&q=80",
    ],
    description: "Personalized bracelet set for you and your best friend. Choose your colors, initials, and charms to create a one-of-a-kind matching set.",
    shortDescription: "Personalized matching bracelet set",
    rating: 5.0,
    reviewCount: 203,
    inStock: true,
    featured: true,
    bestSeller: true,
    tags: ["custom", "friendship", "personalized"],
    materials: ["Glass Beads", "Cotton Thread", "Metal Charms"],
  },
  {
    id: 8,
    name: "Ocean Wave Bracelet",
    price: 42.00,
    category: "bracelets",
    images: [
      "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=800&q=80",
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=80",
    ],
    description: "Inspired by the ocean's gentle waves, this bracelet features aquamarine and turquoise beads with silver accents.",
    shortDescription: "Aquamarine and turquoise ocean-inspired",
    rating: 4.7,
    reviewCount: 54,
    inStock: true,
    tags: ["ocean", "aquamarine", "turquoise"],
    materials: ["Aquamarine", "Turquoise", "Sterling Silver"],
  },
  {
    id: 9,
    name: "Vintage Charm Necklace",
    price: 72.00,
    category: "necklaces",
    images: [
      "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=800&q=80",
      "https://images.unsplash.com/photo-1611652022419-a9419f74343d?w=800&q=80",
    ],
    description: "A nostalgic piece featuring vintage-style glass beads and antique-finish metal charms. Each necklace tells a story.",
    shortDescription: "Vintage glass beads with antique charms",
    rating: 4.6,
    reviewCount: 41,
    inStock: true,
    tags: ["vintage", "charm", "nostalgic"],
    materials: ["Glass Beads", "Antique Brass"],
  },
  {
    id: 10,
    name: "Cherry Blossom Earrings",
    price: 36.00,
    category: "earrings",
    images: [
      "https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=800&q=80",
      "https://images.unsplash.com/photo-1630019852942-f89202989a59?w=800&q=80",
    ],
    description: "Delicate pink and white beads arranged in a cherry blossom pattern. Perfect for spring and everyday wear.",
    shortDescription: "Pink and white cherry blossom design",
    rating: 4.8,
    reviewCount: 67,
    inStock: true,
    tags: ["cherry blossom", "pink", "spring"],
    materials: ["Glass Beads", "Gold Fill"],
  },
  {
    id: 11,
    name: "Sapphire Night Bracelet",
    price: 58.00,
    category: "bracelets",
    images: [
      "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800&q=80",
      "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=800&q=80",
    ],
    description: "Deep blue sapphire beads that catch the light beautifully, paired with silver accents for a sophisticated evening look.",
    shortDescription: "Deep blue sapphire with silver",
    rating: 4.9,
    reviewCount: 88,
    inStock: true,
    tags: ["sapphire", "blue", "evening"],
    materials: ["Sapphire", "Sterling Silver"],
  },
  {
    id: 12,
    name: "Custom Name Necklace",
    price: 85.00,
    category: "custom",
    images: [
      "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=800&q=80",
      "https://images.unsplash.com/photo-1601121141461-9d6647bca1ed?w=800&q=80",
    ],
    description: "A personalized necklace featuring your name or word of choice, crafted with delicate beads and a custom charm.",
    shortDescription: "Personalized name necklace",
    rating: 5.0,
    reviewCount: 178,
    inStock: true,
    featured: true,
    bestSeller: true,
    tags: ["custom", "personalized", "name"],
    materials: ["14k Gold Fill", "Glass Beads"],
  },
];

export const collections = [
  {
    id: 'bracelets',
    name: 'Bracelets',
    image: 'https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=600&q=80',
    description: 'Handcrafted bracelets for every occasion',
    count: products.filter(p => p.category === 'bracelets').length,
  },
  {
    id: 'necklaces',
    name: 'Necklaces',
    image: 'https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&q=80',
    description: 'Elegant necklaces to complete your look',
    count: products.filter(p => p.category === 'necklaces').length,
  },
  {
    id: 'earrings',
    name: 'Earrings',
    image: 'https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=600&q=80',
    description: 'Beautiful earrings that make a statement',
    count: products.filter(p => p.category === 'earrings').length,
  },
  {
    id: 'custom',
    name: 'Custom Orders',
    image: 'https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=600&q=80',
    description: 'Personalized pieces made just for you',
    count: products.filter(p => p.category === 'custom').length,
  },
];

export const reviews = [
  {
    id: 1,
    name: "Sarah Johnson",
    avatar: "https://i.pravatar.cc/150?img=1",
    rating: 5,
    date: "2 weeks ago",
    comment: "Absolutely stunning bracelet! The craftsmanship is incredible and it arrived beautifully packaged. Will definitely order again!",
    product: "Rose Quartz Love Bracelet",
  },
  {
    id: 2,
    name: "Emily Chen",
    avatar: "https://i.pravatar.cc/150?img=5",
    rating: 5,
    date: "1 month ago",
    comment: "The pearl necklace is even more beautiful in person. Perfect for my wedding day. Thank you for creating such a special piece!",
    product: "Pearl Elegance Necklace",
  },
  {
    id: 3,
    name: "Maria Garcia",
    avatar: "https://i.pravatar.cc/150?img=9",
    rating: 5,
    date: "3 weeks ago",
    comment: "I ordered custom bracelets for my bridesmaids and they were absolutely perfect. Everyone loved them! Amazing quality and service.",
    product: "Custom Friendship Bracelet Set",
  },
  {
    id: 4,
    name: "Jessica Williams",
    avatar: "https://i.pravatar.cc/150?img=16",
    rating: 5,
    date: "1 week ago",
    comment: "The moonstone bracelet is magical! It catches the light beautifully and I get compliments every time I wear it.",
    product: "Moonstone Magic Bracelet",
  },
];

export const instagramPosts = [
  "https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=400&q=80",
  "https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?w=400&q=80",
  "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=400&q=80",
  "https://images.unsplash.com/photo-1535632787350-4e68ef0ac584?w=400&q=80",
  "https://images.unsplash.com/photo-1602173574767-37ac01994b2a?w=400&q=80",
  "https://images.unsplash.com/photo-1573408301185-9146fe634ad0?w=400&q=80",
  "https://images.unsplash.com/photo-1622398925373-3f91b1e275f5?w=400&q=80",
  "https://images.unsplash.com/photo-1599643477877-530eb83abc8e?w=400&q=80",
];